name: Testing

on: [push, pull_request]

jobs:
  matlab-tests:
    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        /usr/local/bin/matlab -nodisplay -nosplash -nodesktop -r "addpath(genpath('.'));  cd('testing/unit_tests'); runtests(struct2table(dir('*.m')).name); exit;" 
